### ISSUE TITLE
Build from Amplify Console fails

### ISSUE THREAD

**Issue by panayi** [aws-samples/aws-amplify-quick-notes#3]
Deploying from https://console.aws.amazon.com/amplify/home?region=us-east-1 fails with the following build log:

```
2020-07-27T19:15:50.314Z [INFO]: Git SSH Key acquired
2020-07-27T19:15:50.386Z [INFO]: # Cloning repository: git@github.com:panayi/aws-amplify-quick-notes.git
2020-07-27T19:15:50.654Z [INFO]: Agent pid 122
2020-07-27T19:15:50.659Z [INFO]: Identity added: /root/.ssh/git_rsa (/root/.ssh/git_rsa)
2020-07-27T19:15:50.931Z [INFO]: Cloning into 'aws-amplify-quick-notes'...
2020-07-27T19:15:51.469Z [INFO]: Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
2020-07-27T19:15:51.746Z [INFO]: # Checking for Git submodules at: /codebuild/output/src385148478/src/aws-amplify-quick-notes/.gitmodules
2020-07-27T19:15:51.851Z [INFO]: # Retrieving cache...
2020-07-27T19:15:51.901Z [INFO]: # Extracting cache...
2020-07-27T19:15:51.909Z [INFO]: # Extraction completed
2020-07-27T19:15:51.910Z [INFO]: # Retrieving environment cache...
2020-07-27T19:15:51.957Z [INFO]: # Retrieved environment cache
2020-07-27T19:15:51.959Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'canary'
2020-07-27T19:16:01.286Z [INFO]: # Patching NPM package '@aws-amplify/cli' from 1.12.0 to canary...
2020-07-27T19:16:50.019Z [INFO]: # Done patching NPM package '@aws-amplify/cli'
2020-07-27T19:16:53.761Z [INFO]: ## Starting Backend Build
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2020-07-27T19:16:53.766Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2020-07-27T19:16:53.771Z [INFO]: # Start initializing Amplify environment: deve
2020-07-27T19:16:53.772Z [INFO]: # Initializing new Amplify environment: deve (amplify init)
2020-07-27T19:16:54.619Z [INFO]: Project path: '/Users/kemplk/Projects/quick-notes' does not exist.
2020-07-27T19:16:54.620Z [INFO]: Error: Project path: '/Users/kemplk/Projects/quick-notes' does not exist.
                                 at Function.FeatureFlags.initialize (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:246:15)
2020-07-27T19:16:55.469Z [INFO]: Project path: '/Users/kemplk/Projects/quick-notes' does not exist.
2020-07-27T19:16:55.470Z [INFO]: Error: Project path: '/Users/kemplk/Projects/quick-notes' does not exist.
                                 at Function.FeatureFlags.initialize (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-cli-core/lib/feature-flags/featureFlags.js:246:15)
2020-07-27T19:16:55.476Z [ERROR]: !!! Build failed
2020-07-27T19:16:55.599Z [ERROR]: !!! Non-Zero Exit Code detected
2020-07-27T19:16:55.599Z [INFO]: # Starting environment caching...
2020-07-27T19:16:55.600Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by litwicki** [comment]
@panayi we will be updating this repo for these changes shortly, but in the meantime, the app needs to be updated to reflect your environment, not the one mistakenly in the repo here.

1. Update .gitignore:

```
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplify-gradle-config.json
amplifyxc.config
```

2. Delete these files/folders:

```
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplify-gradle-config.json
amplifyxc.config
```

Using the Amplify CLI: 

3. Run a fresh `amplify init`
4. Run `amplify push`

Please let me know if you have any additional issues.

**Comment by garyleefight** [comment]
Let us know if you still have issue

**Comment by panayi** [comment]
Thanks! Opened #6 (although only #5 is needed to fix the deploy).
